#!/bin/bash

# A script that will ask for a number and print out a message depending on the value. 

read -p "Enter a number: " n
case $n in
    1|2) 
        echo "One or two";;
    [3-9]) 
        echo "Three to nine";;
    ??) 
        echo "Two characters";;
    *.txt) 
        echo "End in .txt";;
    *) 
        echo "Other";;
esac
    