#!/bin/bash

# Welcome to your first Bash Script

hello_message='Hello World!'
current_dir=$(pwd)
readonly variable_wont_change='blue'
variable_wont_change='red'

echo "$hello_message from $current_dir you fav color is $variable_wont_change"