#!/bin/bash

check_even () {
    local mod=2
    echo "The value of mod is $mod"
    if [ $(("$2" % $mod)) -eq 0 ]
    then 
       echo "The number $2 is even!";
    else 
       echo "The number $2 is odd!"
    fi
}


first_number=2344
second_number=11

check_even $first_number $second_number
echo "the value outside function: $mod"